base: remove Unix time dependency temporarily
Remove Unix time code from Owl_base.

This is needed because MirageOS failed to be built as:

 Error: No implementations provided for the following modules:
          Unix referenced from /home/ehirdoy/.opam/4.06.1+lto/lib/owl-base/owl_base.cmxa(Owl_utils),
            /home/ehirdoy/.opam/4.06.1+lto/lib/owl-base/owl_base.cmxa(Owl_log),
            /home/ehirdoy/.opam/4.06.1+lto/lib/owl-base/owl_base.cmxa(Owl_io)

This can be temporary workaround.
Other non-unix time function could revert this commit later.

Signed-off-by: Hiroshi Doyu <hiroshi.doyu@ericsson.com>